openCL_Pierce:  openCL_Pierce.c
	cc -Wall -O2 -std=c99 openCL_Pierce.c -o openCL_Pierce -L/usr/local/cuda/lib64 -lOpenCL

openCL_List_Specs:  openCL_List_Specs.c
	cc -Wall -O2 -std=c99 openCL_List_Specs.c -o openCL_List_Specs -L/usr/local/cuda/lib64 -lOpenCL
