#
# makefile for the first assignment
#

clean:
	rm -f a.out d_plain v3_threads

v3_plain:	count_sum_free_sets_v3_plain.c
	cc -Wall -O2 -Wextra -Wundef          count_sum_free_sets_v3_plain.c   -o v3_plain

v3_plain_all:	count_sum_free_sets_v3_plain_all.c
	cc -Wall -O2 -Wextra -Wundef          count_sum_free_sets_v3_plain_all.c   -o v3_plain_all