#
# makefile for the first assignment
#

clean:
	rm -f a.out v2_plain v2_threads

v2_plain:	count_sum_free_sets_v2_plain.c
	cc -Wall -O2 -Wextra -Wundef          count_sum_free_sets_v2_plain.c   -o v2_plain